databases:
  - name: RestartFashion_DB
    databaseName: restartfashion_db
    user: ReStartFashion
    region: singapore

services:
  - type: web
    name: ReStartFashion
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: RestartFashion_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

